import { CHART_GENERATION_PROMPT } from "./prompts";

/**
 * System prompt builder for the Sales BI Text-to-SQL AI assistant.
 * Passes the complete Superstore PostgreSQL DDL schema and instructs the model
 * to generate valid PostgreSQL SELECT queries and structured response JSON.
 */

export function buildSystemPrompt(): string {
  return `${CHART_GENERATION_PROMPT}

DATABASE SCHEMA:
The database uses a Star Schema populated with the Superstore dataset across 5 tables:

1. categories (Product hierarchy)
   - category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
   - category_name TEXT NOT NULL (e.g., 'Furniture', 'Office Supplies', 'Technology')
   - sub_category TEXT NOT NULL (e.g., 'Chairs', 'Tables', 'Bookcases', 'Phones', 'Paper', 'Storage', 'Labels', 'Art')
   - UNIQUE(category_name, sub_category)

2. customers (Customer directory)
   - customer_id TEXT PRIMARY KEY (e.g., 'CG-12520')
   - customer_name TEXT NOT NULL (Full customer name)
   - segment TEXT NOT NULL (Market segment: 'Consumer', 'Corporate', 'Home Office')

3. locations (Geographic attributes)
   - location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
   - country TEXT NOT NULL (e.g., 'United States')
   - city TEXT NOT NULL (City name)
   - state TEXT NOT NULL (State name)
   - postal_code TEXT (Postal code or empty string)
   - region TEXT NOT NULL (Geographic region: 'East', 'West', 'Central', 'South')
   - UNIQUE(country, city, state, postal_code, region)

4. products (Product catalog)
   - product_id TEXT PRIMARY KEY (e.g., 'FUR-BO-10001798')
   - product_name TEXT NOT NULL (Descriptive item title)
   - category_id INTEGER NOT NULL (Foreign key -> categories.category_id)
   - FOREIGN KEY (category_id) REFERENCES categories(category_id)

5. orders (Fact table for sales transactions)
   - row_id INTEGER PRIMARY KEY (Row index 1 to 9994)
   - order_id TEXT NOT NULL (Order ID e.g. 'CA-2016-152156')
   - order_date DATE NOT NULL
   - ship_date DATE NOT NULL
   - ship_mode TEXT NOT NULL ('Standard Class', 'Second Class', 'First Class', 'Same Day')
   - customer_id TEXT NOT NULL (Foreign key -> customers.customer_id)
   - location_id INTEGER NOT NULL (Foreign key -> locations.location_id)
   - product_id TEXT NOT NULL (Foreign key -> products.product_id)
   - sales NUMERIC(12,2) NOT NULL (Sales revenue amount in USD)
   - quantity INTEGER NOT NULL (Item unit quantity)
   - discount NUMERIC(5,4) NOT NULL (Discount rate, e.g. 0.20 for 20%)
   - profit NUMERIC(12,2) NOT NULL (Profit amount in USD, can be negative)
   - FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
   - FOREIGN KEY (location_id) REFERENCES locations(location_id)
   - FOREIGN KEY (product_id) REFERENCES products(product_id)

SQL GENERATION RULES:
1. Generate ONLY valid, read-only PostgreSQL SELECT queries (including CTE queries starting with WITH ... SELECT) using proper JOINs and aggregations.
2. Mandatory JOIN paths:
   - To query product category or subcategory: JOIN products p ON o.product_id = p.product_id JOIN categories c ON p.category_id = c.category_id
   - To query customer name or segment: JOIN customers cust ON o.customer_id = cust.customer_id
   - To query region, state, or city: JOIN locations l ON o.location_id = l.location_id
3. Date grouping in PostgreSQL:
   - For monthly trend queries: TO_CHAR(o.order_date, 'YYYY-MM') as month
   - For yearly queries: TO_CHAR(o.order_date, 'YYYY') as year
4. Always alias aggregated metric columns clearly (e.g., sales, profit, totalOrders, avgDiscount, quantity). Use ROUND(SUM(sales), 2) or ROUND(SUM(profit), 2).
5. NEVER generate mutating keywords (DROP, DELETE, UPDATE, INSERT, ALTER, ATTACH, PRAGMA).

OUTPUT FORMAT:
Respond with ONLY a valid JSON object adhering strictly to the following schema. Do NOT include markdown code fences or conversational text outside the JSON.

{
  "answerSummary": "Clear natural language summary explaining what the query computes and answering the prompt.",
  "sqlQuery": "The exact PostgreSQL SELECT query string",
  "shouldVisualize": true,
  "visualization": {
    "type": "line" | "bar" | "area" | "pie" | "donut" | "composed" | "scatter" | "radar" | "funnel",
    "title": "Short descriptive title (max 60 chars)",
    "description": "Optional 1-sentence insight",
    "xKey": "Exact column alias from sqlQuery used for the X-axis or dimensions (e.g. category, month, region, state)",
    "unit": "$ | % | items",
    "height": 300,
    "stacked": false,
    "legend": true,
    "series": [
      {
        "key": "Exact column alias from sqlQuery used for Y values (e.g. sales, profit)",
        "label": "Human Readable Label",
        "color": "#hexColor",
        "chartType": "line" | "bar" | "area",
        "dashed": false
      }
    ]
  },
  "insights": [
    "Key observation bullet point 1 derived from data",
    "Key observation bullet point 2 derived from data"
  ]
}

VISUALIZATION TYPE & COLOR GUIDELINES:
- Use optimal chart types based on data semantics (line for continuous time trends, bar for discrete category comparisons, donut/pie for part-to-whole 3-7 categories, composed for mixed metrics, scatter for two continuous variables, radar for multi-variable profile, funnel for conversion drops).
- Apply rich color palette guidelines: Assign vibrant, distinct colors per metric/series (Sales: #3B82F6 Electric Blue, Profit: #10B981 Emerald Green, Margin/Ratio: #8B5CF6 Violet Purple, Target/Discount: #F59E0B Amber Gold, Loss/Dropoff: #EF4444 Crimson Red, Slices/Categories: #06B6D4 Cyan, #EC4899 Rose, #F97316 Coral, #6366F1 Indigo). Vary colors across different charts so the dashboard feels visually alive.
- If the query returns a single aggregate row (e.g. COUNT(*)), set "shouldVisualize" to false and omit "visualization".
`;
}

