import { Pool } from "pg";
import { loadEnvConfig } from "@next/env";

loadEnvConfig(process.cwd());

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is missing from the server environment.");
}

export const db = new Pool({
  connectionString: process.env.DATABASE_URL,
  max: 10,
  idleTimeoutMillis: 30_000,
  connectionTimeoutMillis: 10_000,
});

export async function initDatabase(): Promise<void> {
  await db.query(`
    CREATE TABLE IF NOT EXISTS categories (
      category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category_name TEXT NOT NULL,
      sub_category TEXT NOT NULL,
      UNIQUE (category_name, sub_category)
    );
    CREATE TABLE IF NOT EXISTS customers (
      customer_id TEXT PRIMARY KEY,
      customer_name TEXT NOT NULL,
      segment TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS locations (
      location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      country TEXT NOT NULL,
      city TEXT NOT NULL,
      state TEXT NOT NULL,
      postal_code TEXT,
      region TEXT NOT NULL,
      UNIQUE (country, city, state, postal_code, region)
    );
    CREATE TABLE IF NOT EXISTS products (
      product_id TEXT PRIMARY KEY,
      product_name TEXT NOT NULL,
      category_id INTEGER NOT NULL REFERENCES categories(category_id)
    );
    CREATE TABLE IF NOT EXISTS orders (
      row_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id TEXT NOT NULL,
      order_date DATE NOT NULL,
      ship_date DATE NOT NULL,
      ship_mode TEXT NOT NULL,
      customer_id TEXT NOT NULL REFERENCES customers(customer_id),
      location_id INTEGER NOT NULL REFERENCES locations(location_id),
      product_id TEXT NOT NULL REFERENCES products(product_id),
      sales NUMERIC(12, 2) NOT NULL,
      quantity INTEGER NOT NULL,
      discount NUMERIC(5, 4) NOT NULL,
      profit NUMERIC(12, 2) NOT NULL
    );
  `);
}
